import type { ExhibitionConfig } from '../types/exhibit';

export const defaultConfig: ExhibitionConfig = {
  exhibition: {
    title: '数据安全评估服务成果展',
    subtitle: '专业能力 · 项目案例 · 成果质量',
    description: '欢迎参观数据安全评估服务数字化展厅',
  },
  scene: {
    backgroundColor: '#0a0a1a',
    floorSize: [20, 20],
    wallHeight: 4,
  },
  exhibits: [
    {
      id: 'report-001',
      title: '安全评估报告',
      subtitle: '2024年度数据安全评估',
      description: '2024年度数据安全评估总报告',
      detailContent: '本报告涵盖了企业数据安全现状的全面评估，包括数据分类分级、访问控制、加密措施等核心维度的评估结果。',
      type: 'image',
      mediaSrc: '/assets/images/placeholder-report.jpg',
      position: [-6, 1.5, -9],
      rotation: [0, 0.2, 0],
      scale: 1.2,
      category: 'report',
      order: 1,
    },
    {
      id: 'video-001',
      title: '项目纪实',
      subtitle: '全流程记录视频',
      description: '数据安全评估服务全流程记录',
      detailContent: '本视频记录了数据安全评估服务从启动到交付的完整过程。',
      type: 'video',
      mediaSrc: '/assets/videos/placeholder-video.mp4',
      previewImage: '/assets/images/placeholder-video.jpg',
      position: [0, 1.5, -9],
      rotation: [0, 0, 0],
      scale: 1.5,
      category: 'video',
      order: 1,
    },
    {
      id: 'doc-001',
      title: '安全体系文档',
      subtitle: '企业数据安全管理体系',
      description: '建立的企业数据安全管理体系',
      detailContent: '本次评估帮助客户建立了完整的数据安全管理体系，涵盖组织架构、制度流程、技术措施三大板块。',
      type: 'document',
      mediaSrc: '/assets/documents/placeholder.pdf',
      previewImage: '/assets/images/placeholder-doc.jpg',
      position: [6, 1.5, -9],
      rotation: [0, -0.2, 0],
      scale: 1,
      category: 'document',
      order: 1,
    },
    {
      id: 'achievement-001',
      title: '成果展示',
      subtitle: '数据安全防护体系成果',
      description: '数据安全评估服务核心成果',
      detailContent: '通过本次评估，帮助客户建立了完整的数据安全防护体系，显著提升了数据安全水平。',
      type: 'image',
      mediaSrc: '/assets/images/placeholder-achievement.jpg',
      position: [0, 1.5, 9],
      rotation: [0, Math.PI, 0],
      scale: 1.5,
      category: 'achievement',
      order: 1,
    },
  ],
  tourRoute: [
    {
      position: [0, 1.7, 5],
      lookAt: [0, 1.5, 0],
      duration: 1000,
    },
    {
      position: [-6, 1.7, -6],
      lookAt: [-6, 1.5, -9],
      duration: 2000,
      exhibitId: 'report-001',
    },
    {
      position: [0, 1.7, -6],
      lookAt: [0, 1.5, -9],
      duration: 2000,
      exhibitId: 'video-001',
    },
    {
      position: [6, 1.7, -6],
      lookAt: [6, 1.5, -9],
      duration: 2000,
      exhibitId: 'doc-001',
    },
    {
      position: [0, 1.7, 6],
      lookAt: [0, 1.5, 9],
      duration: 2000,
      exhibitId: 'achievement-001',
    },
  ],
  cameraStart: {
    position: [0, 1.7, 5],
    lookAt: [0, 1.5, 0],
  },
};
